version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "DockerSQL2022_"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Standard"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9260:8080"
      - "9261:443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/api.pfx
      # This connection string is for inside the Docker network!
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=movieaspcore;User Id=sa;Password=DockerSQL2022_;TrustServerCertificate=true;
    volumes:
      - uploads_data:/app/wwwroot
      - ${HOME}/.aspnet/https:/https:ro
    networks:
      - app-network

volumes:
  sqlserver_data:
  uploads_data:

networks:
  app-network:
